name: Deploy to NPM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        continue-on-error: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
        continue-on-error: false

      - name: Install Dependencies
        run: npm install
        continue-on-error: false

      - name: Build
        run: npm run build
        continue-on-error: false

      - name: Check Git Version
        run: git --version
        continue-on-error: false

      - name: Check npm Version
        run: npm --version
        continue-on-error: false

      - name: Authenticate with NPM
        run: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        continue-on-error: false

      - name: Change Directory to dist
        run: cd dist/sid-library-ng
        continue-on-error: false

      - name: View Dist Contents
        run: ls -R dist
        continue-on-error: false

      - name: Create NPM Package
        run: npm pack
        continue-on-error: false


      - name: Publish to NPM
        run: npm publish sid-library-ng-*.tgz
        continue-on-error: false

      - name: Push Version Update
        run: git push origin main --follow-tags
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        continue-on-error: false
