name: Deploy to NPM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install 

      - name: Build
        run: npm run build

      - name: Update Version
        run: |
          git config --global user.email "sidhanthkundu16@gmail.com"
          git config --global user.name "sidhanthkundu16"
          npm version patch
        id: version
        shell: bash

      - name: Authenticate with NPM
        run: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to NPM
        run: npm publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'

      - name: Push Version Update
        run: git push origin main --follow-tags
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
